AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 82
  Exclude:
    - "spec/**/*"

Layout/SpaceAroundOperators:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  CountComments: true
  Max: 25
  IgnoredMethods: []
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10

Metrics/ParameterLists:
  Max: 6

Metrics/MethodLength:
  Max: 20

Style/AccessorGrouping:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

# { ... } for multi-line blocks is okay
Style/BlockDelimiters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Multiline lambdas are fine too
Style/LambdaCall:
  Enabled: false

# I find the == 0 quite readable due to many years of programming habits
Style/NumericPredicate:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
